version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  node_backend:
    image: node:18
    container_name: node_backend
    working_dir: /usr/src/app/backend
    volumes:
      - .:/usr/src/app
    environment:
      MONGO_URI: "mongodb+srv://eliran0220:9GSWgaJIjgV3GgMk@cluster0.nlfgy.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - app_network
    command: ["node", "server.js"]

volumes:
  redis_data:

networks:
  app_network: # Define a custom network for inter-service communication
    driver: bridge
